### ISSUE TITLE
Support for QuitAll tweak with iPad grid

### ISSUE THREAD

**Issue by iluwQaa** [tomaszpoliszuk/AppSwitcherController#2]
[Tweak link](https://chariz.com/get/quitall) 
[GitHub link](https://github.com/vanwijkdave/QuitAll)

**Comment by tomaszpoliszuk** [comment]
Could you please describe what's wrong?

**Comment by iluwQaa** [comment]
close button didn't appear. at now cannot test with latest updates. close issue
